swagger: '2.0'
info:
  description: 'person api'
  version: 1.0.0
  title: Swagger
host: local
basePath: /v1
tags:
  - name: person
    description: Operations about user
    externalDocs:
      description: Find out more about our person
      url: http://swagger.io
schemes:
  - https
  - http
paths:
  /person:
    get:
      tags:
        - person
      summary: Get all people in database
      description: ''
      operationId: getAllPeople
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    post:
      tags:
        - person
      summary: Post one people in database
      description: ''
      operationId: postOnePerson
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    put:
      tags:
        - person
      summary: Put one people in database
      description: ''
      operationId: puttOnePerson
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    delete:
      tags:
        - person
      summary: Delete one people in database
      description: ''
      operationId: deleteOnePerson
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found


definitions:
  Person:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
