swagger: '2.0'
info:
  description: 'person api'
  version: 1.0.0
  title: Swagger
host: local
basePath: /v1
tags:
  - name: person
    description: Operations about user
    externalDocs:
      description: Find out more about our person
      url: http://swagger.io
schemes:
  - https
  - http
paths:
  /person:
    get:
      tags:
        - person
      summary: Get all people in database
      description: ''
      operationId: getAllPeople
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    post:
      tags:
        - person
      summary: Post one person in database
      description: ''
      operationId: postOnePerson
      produces:
        - application/json
        - application/xml
      responses:
        '201':
          description: created
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    put:
      tags:
        - person
      summary: Put one person in database
      description: ''
      operationId: puttOnePerson
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    delete:
      tags:
        - person
      summary: Delete one person in database
      description: ''
      operationId: deleteOnePerson
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
  /person/{personId}:
    get:
      tags:
        - person
      summary: Find person by ID
      description: Returns a single person
      operationId: getPesonById
      produces:
        - application/json
        - application/xml
      parameters:
        - name: personId
          in: path
          description: ID of person to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        '400':
          description: Invalid ID supplied
        '404':
          description: Person not found
    post:
      tags:
        - person
      summary: Updates a person in the store with form data
      description: ''
      operationId: updatePetWithForm
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
        - application/xml
      parameters:
        - name: personId
          in: path
          description: ID of pet that needs to be updated
          required: true
          type: integer
          format: int64
        - name: name
          in: formData
          description: Updated name of the person
          required: false
          type: string
        - name: status
          in: formData
          description: Updated status of the person
          required: false
          type: string
      responses:
        '405':
          description: Invalid input
    delete:
      tags:
        - person
      summary: Deletes a person
      description: ''
      operationId: deletePerson
      produces:
        - application/json
        - application/xml
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: personId
          in: path
          description: Person id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Person not found

definitions:
  Person:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
